### ISSUE TITLE
Crashing of Acts.

### ISSUE THREAD

**Issue by DEVDD960** [perpetualKid/ORTS-MG#124] opened 2023-03-08 07:47 UTC
[OpenRailsLog.txt](https://github.com/perpetualKid/ORTS-MG/files/10918349/OpenRailsLog.txt)

This act got crashed during the load. The same act works perfectly fine on other versions. I hope the issue gets rectified. 
----------------------- 
Second Crash: 
[OpenRailsLog.txt](https://github.com/perpetualKid/ORTS-MG/files/10919368/OpenRailsLog.txt) 

This time the act loaded perfecty, but when i tried to open Map Window( Ctrl+9) in the middle of the Act it crashes.

**Comment by perpetualKid** [comment] 2023-03-08 09:54
the error in the log has nothing to do with specific activities or routes, but input device capabilities. 
So it may happen with (all) other routes/activities as well.
I'll put a check in the specific code to prevent crashing, although not yet understanding what triggers the exception at all.

**Comment by DEVDD960** [comment] 2023-03-08 09:58
> the error in the log has nothing to do with specific activities or routes, but input device capabilities. So it may happen with (all) other routes/activities as well. I'll put a check in the specific code to prevent crashing, although not yet understanding what triggers the exception at all.

ok, please check the second crash log also, this time it crashed in between.

**Comment by perpetualKid** [comment] 2023-03-08 10:24
I've added two checks to prevent the specific situation, as update 1.4.13-dev.45 in the developers channel momentarily.

Looking at the specs, could it be your machine is under memory pressure, is this a large route? Both may be caused by some race condition in code not yet observed/reported by other users, so wondering what is the root cause here.

**Comment by DEVDD960** [comment] 2023-03-08 10:43
> I've added two checks to prevent the specific situation, as update 1.4.13-dev.45 in the developers channel momentarily.
> 
> Looking at the specs, could it be your machine is under memory pressure, is this a large route? Both may be caused by some race condition in code not yet observed/reported by other users, so wondering what is the root cause here.

I agree that the route is heavy, but its also optimized properly and yes, reshade started working, I directed the installation to Activity Runner.exe , due to this the reshade overlay also activates on dispatcher window, I tried it again, and observed that the act only crashes when dispatcher window is opened, but I guess it has nothing to do with reshade, as I remember earlier also it crashed after sometime when the dispatcher window was open when reshade was not loaded.

**Comment by perpetualKid** [comment] 2023-03-09 20:17
if you still experience issues with DispatcherView, I suggest to open a new issue and attach appropriate log file, and we close this current issue as resolved?

**Closed** 2023-03-12 21:12 UTC
