### ISSUE TITLE
Cannot resume session when AI trains present

### ISSUE THREAD

**Issue by HengYeDev** [perpetualKid/ORTS-MG#55] opened 2021-03-25 14:07 UTC
When I try to resume a session, the loading screen appears then this happens:

![image](https://user-images.githubusercontent.com/62600441/112491249-826fc900-8d56-11eb-9c8d-cd989950c0b2.png)

**Comment by HengYeDev** [comment] 2021-03-25 14:35
However, logging is disabled, So I am in a very bad situation, i cant get the exception log because logging is turned off and when i turn it on WMI complains

**Comment by perpetualKid** [comment] 2021-03-25 14:58
I think the best option for now is to remove WMI - it's only used to get some hardware information, which is not relevant at all for the game at runtime, and only used to provide some information to the logging. There isn't much value lost if you don't get to see the size of the video memory in the game, but maybe only as part of the launcher menu or so. This should also re-enable the logging.
I'll look into it to remove those parts, but will take a few days.

**Comment by HengYeDev** [comment] 2021-03-25 15:00
An even better option would be to have options for turn on/off WMI but that will take some more work

**Comment by HengYeDev** [comment] 2021-03-25 15:32
#56 will simply catch the exceptions I see when logging is enabled.

**Comment by HengYeDev** [comment] 2021-03-25 16:28
OK i have some more information on this since logging is fixed.

When resuming, all the world tiles, signals, crossovers are not correct.

Log: https://gist.github.com/HengYeDev/066ed4642195a328010c84ecf89ad30c

I think the save files might not be correct.

**Comment by HengYeDev** [comment] 2021-03-25 17:48
It does seem like the save doesn't work properly. The picture in the resume/replay window are strange

**Comment by HengYeDev** [comment] 2021-03-25 18:09
Hmm, the world tiles etc also show when not resuming. https://gist.github.com/HengYeDev/35d823bde946594a3203830e39a7a25c

**Comment by HengYeDev** [comment] 2021-03-25 18:15
![image](https://user-images.githubusercontent.com/62600441/112522935-95919180-8d74-11eb-91aa-d6a4abffeaa9.png)

**Comment by perpetualKid** [comment] 2021-03-25 21:55
I can reproduce here as well.

**Comment by perpetualKid** [comment] 2021-03-25 22:54
The screenshots are a differnt thing, but the general error on resume should be fixed now

**Comment by HengYeDev** [comment] 2021-03-25 22:55
Its in monogame branch so my logging fix isn't there...should i create another PR for monogame branch?

**Comment by perpetualKid** [comment] 2021-03-25 22:56
> Its in monogame branch so my logging fix isn't there...should i create another PR for monogame branch?

nope I've already merge that into the Monogame branch as well

**Comment by perpetualKid** [comment] 2021-03-26 11:32
@HengYeDev  feel free to close when you got a chance to confirm this is solved.

**Comment by HengYeDev** [comment] 2021-03-26 12:01
On 1.3.7~8 it doesn't seem like its fixed. I get a different error now @perpetualKid 

```
Error: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadString()
   at Orts.Simulation.AIs.AI..ctor(Simulator simulator, BinaryReader inf) in D:\a\1\s\Source\Orts.Simulation\Simulation\AIs\AI.cs:line 199
   at Orts.Simulation.Simulator.Restore(BinaryReader inf, String pathName, Single initialTileX, Single initialTileZ, CancellationToken cancellation) in D:\a\1\s\Source\Orts.Simulation\Simulation\Simulator.cs:line 526
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.Resume(UserSettings settings) in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\GameStateRunActivity.cs:line 428
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.<>c__DisplayClass27_0.<Load>b__0() in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\GameStateRunActivity.cs:line 166
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.Load() in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\GameStateRunActivity.cs:line 202
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.Load() in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\LoaderProcess.cs:line 160
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.DoLoad() in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\LoaderProcess.cs:line 139
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.LoaderThread() in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\LoaderProcess.cs:line 111
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by HengYeDev** [comment] 2021-03-26 12:06
However the screenshots issue is fixed

**Comment by HengYeDev** [comment] 2021-03-26 12:13
I think the SignalEnv restore got to the end of the file..

**Comment by perpetualKid** [comment] 2021-03-26 12:33
can you try with a new savepoint from the same (new) version? There shouldn't have anything changed wrt to the length of the file, but just to make sure. I can't reproduce that.

**Comment by HengYeDev** [comment] 2021-03-26 12:38
Still have error @perpetualKid

**Comment by HengYeDev** [comment] 2021-03-26 13:01
@perpetualKid I can only reproduce the issue when there are AI trains (i.e. in an activity with AI trains defined)

**Comment by perpetualKid** [comment] 2021-03-26 13:39
I found one issue, but there is still something wrong with AI trains either when saving or restoring, which confuses the serialization format. Needs more time to investigate

**Comment by HengYeDev** [comment] 2021-03-26 16:06
@perpetualKid How did you even get to the NRE? Didn't the binaryreader just stop reading?

**Comment by perpetualKid** [comment] 2021-03-26 22:22
I got the NRE in first place, but that was plausible to fix.
There is some mismatch now what the simuator expects to be in the save file and whats actually read, leading to invalid position in the file or even reading beyond end. The problem is there is no plausibility check between writing and reading, so it may be some additional parameter sneaked in  when writing but is not read correctly, or vice versa more parameters (tried) read than have been written...

**Comment by HengYeDev** [comment] 2021-03-27 00:22
It's got to be the "Start" points...like 199 to resume and 302 to save...so it seems like either the loading of the `AITrain`s when too far in the file or the trains in the StartList don't resume correctly

**Comment by HengYeDev** [comment] 2021-03-27 13:40
I think the current BinaryReader/Writer system is flawed - it can't validate if a value is supposed to be part of an object or not. It would be better if we could do serialization of objects instead in the future.

**Comment by HengYeDev** [comment] 2021-03-27 13:54
@perpetualKid I'm trying to take a look at this by reading source code - in your analysis does `totalStarting` get loaded correctly?

**Comment by perpetualKid** [comment] 2021-03-27 17:47
> I think the current BinaryReader/Writer system is flawed - it can't validate if a value is supposed to be part of an object or not. It would be better if we could do serialization of objects instead in the future.

indeed. this is all legacy code which in my mind would benefit from refactoring. My initial thought was some json-kind format, readable and more resilient to format changes (added/removed properties). However no work done so far

**Comment by HengYeDev** [comment] 2021-03-27 19:03
any luck on the end of stream? my first thought was that somehow the totalStarting was not what it was supposed to be?

**Comment by perpetualKid** [comment] 2021-03-27 21:39
this should be fixed now, but can't be sure yet if there are no other issues. Hopefully we could refactor this code at some point to make it more robust

**Comment by HengYeDev** [comment] 2021-03-27 21:58
as long as the variables are standard (int, string, double, no crazy formats) https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to could be utilized

**Comment by HengYeDev** [comment] 2021-03-27 22:06
Seems fixed for me, thanks. close?

**Closed** 2021-03-27 22:10 UTC
Labels: .NET Core, bug
